version: '3'

services:
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx/nginx-local-frontend-dev.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - api
  
  # frontend:
  #   image: frontend
  #   env_file:
  #     - .env
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./frontend/
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
  # #   # depends_on:
  # #   #   - api

  api:
    image: api
    ports:
      - 8001:8000
      - 5678:5678
    restart: unless-stopped
    volumes:
      - ./api/hydroprocess_db:/hydroprocess_db
    build:
      context: ./api/
      dockerfile: Dockerfile
    working_dir: /hydroprocess_db
    command: python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn --host 0.0.0.0 --port 8000 --proxy-headers main:app --reload
    env_file:
      - .env